-- params : ...

local Constants = require(game.ReplicatedStorage:WaitForChild("Constants"))
return {
[1] = {Title = "Palm Tree",
	AssetId = 1, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Sand.Value, 
	MinFrequency = 2, 
	MaxFrequency = 5
}, 
[2] = {Title = "Asian Shaped Tree",
	AssetId = 2, 
	AssetType = Constants.ASSET_TYPE.Environment,
	BiomeType = Enum.Material.Grass.Value, 
	MinFrequency = 10, 
	MaxFrequency = 15
},
[3] = {Title = "Small Bush",
	AssetId = 3, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Grass.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10
}, 
[4] = {Title = "Rock",
	AssetId = 4, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.AllBiomes, 
	MinFrequency = 2, 
	MaxFrequency = 3
},
[5] = {Title = "Cherry Tree",
	AssetId = 5, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.LeafyGrass.Value, 
	MinFrequency = 10, 
	MaxFrequency = 15
},
[6] = {Title = "Dead Shrub",
	AssetId = 6, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.Desert, 
	MinFrequency = 2, 
	MaxFrequency = 5
}, 
[7] = {Title = "Cactus",
	AssetId = 7, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.Desert, 
	MinFrequency = 2, 
	MaxFrequency = 3
},
[8] = {Title = "Large Bush",
	AssetId = 8, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Grass.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10
}, 
[9] = {Title = "Bones",
	AssetId = 9, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.Dead, 
	MinFrequency = 3, 
	MaxFrequency = 5
}, 
[10] = {Title = "Curvy Pine",
	AssetId = 10, 
	AssetType = Constants.ASSET_TYPE.Environment,
	BiomeType = Enum.Material.Ground.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10,
},
[11] = {Title = "Curvy Pine 2",
	AssetId = 11, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Ground.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10,
}, 
[12] = {Title = "Dead Tree",
	AssetId = 12, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.Dead, 
	MinFrequency = 2, 
	MaxFrequency = 5,
},
[13] = {Title = "Mushroom Pointy",
	AssetId = 13, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Mud.Value, 
	MinFrequency = 2, 
	MaxFrequency = 5,
},
[14] = {Title = "Mushroom Red",
	AssetId = 14, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Mud.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10,
}, 
[15] = {Title = "Pine Tree",
	AssetId = 15, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.Rock.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10,
},
[16] = {Title = "Plant Bird of Paradise",
	AssetId = 16, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.LeafyGrass.Value, 
	MinFrequency = 3, 
	MaxFrequency = 5,
}, 
[17] = {Title = "Red Flower",
	AssetId = 17, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Enum.Material.LeafyGrass.Value, 
	MinFrequency = 5, 
	MaxFrequency = 10,
},
[18] = {Title = "Snowy Tree",
	AssetId = 18, 
	AssetType = Constants.ASSET_TYPE.Environment, 
	BiomeType = Constants.BIOME.Snowy, 
	MinFrequency = 5, 
	MaxFrequency = 10,
}, 
}
