--@denfeet
--Next AssetId: 0x7e

local Constants = require(game.ReplicatedStorage:WaitForChild("Constants"))
return {
[0x1] = {Title = "EmptyWeapon", 
	AssetId = 0x1, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1081405670",
	ImageRectOffset = Vector2.new(256, 0)}
,
[0x2] = {Title = "EmptyAbility", 
	AssetId = 0x2, 
	AssetType = "Ability", 
	Image = "rbxassetid://1081405670",
	ImageRectOffset = Vector2.new(768, 0)}
,
[0x3] = {Title = "EmptyArmor", 
	AssetId = 0x3, 
	AssetType = "Armor", 
	Image = "rbxassetid://1081405670",
	ImageRectOffset = Vector2.new(0, 0)}
,
[0x4] = {Title = "EmptyAccessory", 
	AssetId = 0x4, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1081405670",
	ImageRectOffset = Vector2.new(512, 0)}
,
[0x6] = {Title = "Energy Staff", 
	AssetId = 0x6, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Staff",
	Tier = 0,
	Description = "A magical staff topped with a white crystal.",
	Projectile = {
		Bullet = "Grey Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 10,
		MaxDamage = 30,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x7] = {Title = "Firebrand Staff", 
	AssetId = 0x7, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Staff",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A staff imbued with potent magical fire.",
	Projectile = {
		Bullet = "Fire Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 10,
		MaxDamage = 30,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x8] = {Title = "Comet Staff", 
	AssetId = 0x8, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449", 
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Staff",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A staff charged with the icy powers of the heavens.",
	Projectile = {
		Bullet = "Water Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 15,
		MaxDamage = 35,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x9] = {Title = "Serpentine Staff", 
	AssetId = 0x9, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Staff",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "A staff powered by the magic of snakes.",
	Projectile = {
		Bullet = "Grass Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 20,
		MaxDamage = 40,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xa] = {Title = "Meteor Staff", 
	AssetId = 0xa, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449", 
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Staff",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "A staff that harnesses the energy of shooting stars.",
	Projectile = {
		Bullet = "Brown Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 25,
		MaxDamage = 45,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xb] = {Title = "Slayer Staff", 
	AssetId = 0xb, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Staff",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "A powerful staff crafted by demons for waging war on mortals.",
	Projectile = {
		Bullet = "Fire Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 35,
		MaxDamage = 55,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x20] = {Title = "Avenger Staff", 
	AssetId = 0x20, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449", 
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Staff",
	Tier = 6,
	BagType = "Brown Bag",
	Description = "A slender felwood staff pulsing with auras of vengeance and justice.",
	Projectile = {
		Bullet = "Water Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 40,
		MaxDamage = 70,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xc] = {Title = "Staff of Destruction", 
	AssetId = 0xc, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Staff",
	Tier = 7,
	BagType = "Brown Bag",
	Description = "An ancient knurlwood staff crackling with power and exuding thin grey vapors.",
	Projectile = {
		Bullet = "Fire Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 45,
		MaxDamage = 85,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xd] = {Title = "Staff of Horror", 
	AssetId = 0xd, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Staff",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "A mysterious runewood staff decorated with horrific figures.",
	Projectile = {
		Bullet = "Brown Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 50,
		MaxDamage = 90,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xe] = {Title = "Staff of Diabolic Secrets", 
	AssetId = 0xe, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449", 
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Staff",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "An imposing golden staff of tremendous otherworldly power.",
	Projectile = {
		Bullet = "Water Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 55,
		MaxDamage = 95,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0xf] = {Title = "Staff of Astral Knowledge", 
	AssetId = 0xf, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Staff",
	Tier = 10,
	BagType = "Blue Bag",
	Description = "A splendid golden staff of astonishing power, bathed in light and brimming with magical energy.",
	Projectile = {
		Bullet = "Grass Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 55,
		MaxDamage = 100,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x10] = {Title = "Staff of the Cosmic Whole", 
	AssetId = 0x10, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449", 
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Staff",
	Tier = 11,
	BagType = "White Bag",
	Description = "A golden staff of transcendent understanding, made from crystals present at the formation of universe.",
	Projectile = {
		Bullet = "Pink Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 60,
		MaxDamage = 100,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x11] = {Title = "Staff of Vital Unity", 
	AssetId = 0x11, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1079004449",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Staff",
	Tier = 12,
	BagType = "White Bag",
	Description = "A golden staff of elysian consciousness, shining with the base power of empyrean truths.",
	Projectile = {
		Bullet = "Gold Missile",
		Range = 8.55*Constants.STATS.TileSize,
		MinDamage = 60,
		MaxDamage = 105,
		Lifetime = 8.55*Constants.STATS.TileSize/28,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x12] = {Title = "Short Sword", 
	AssetId = 0x12, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Sword",
	Tier = 0,
	Description = "A steel short sword.",
	Projectile = {
		Bullet = "Blade",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 45,
		MaxDamage = 90,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x13] = {Title = "Broad Sword", 
	AssetId = 0x13, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Sword",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A broad-bladed steel sword.",
	Projectile = {
		Bullet = "Blade",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 60,
		MaxDamage = 105,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x14] = {Title = "Long Sword", 
	AssetId = 0x14, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Sword",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A well-made sword with a double edged blade.",
	Projectile = {
		Bullet = "Blade",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 75,
		MaxDamage = 120,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x15] = {Title = "Falchion Sword", 
	AssetId = 0x15, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Sword",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "A single-edged broad-bladed sword.",
	Projectile = {
		Bullet = "Blade",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 75,
		MaxDamage = 135,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x16] = {Title = "Fire Sword", 
	AssetId = 0x16,
	AssetType = "Weapon",
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Sword",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "A fiery blade capable of burning flesh and bone.",
	Projectile = {
		Bullet = "Fire Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 90,
		MaxDamage = 135,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x17] = {Title = "Glass Sword", 
	AssetId = 0x17, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Sword",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "A sword formed from a single shard of unbreakable glass.",
	Projectile = {
		Bullet = "White Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 30,
		MaxDamage = 210,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x18] = {Title = "Golden Sword", 
	AssetId = 0x18, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Sword",
	Tier = 6,
	BagType = "Blue Bag",
	Description = "A sharp sword plated with gold, clearly intended for the use of a great lord.",
	Projectile = {
		Bullet = "Blade",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 150,
		MaxDamage = 180,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x19] = {Title = "Ravenheart Sword", 
	AssetId = 0x19, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Sword",
	Tier = 7,
	BagType = "Blue Bag",
	Description = "A powerful sword infused with the spirit of dark rituals.",
	Projectile = {
		Bullet = "Darkness Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 180,
		MaxDamage = 255,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1a] = {Title = "Dragonsoul Sword", 
	AssetId = 0x1a, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Sword",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "A sword forged in a great volcano and consecrated with dragon magic.",
	Projectile = {
		Bullet = "White Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 195,
		MaxDamage = 255,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1b] = {Title = "Archon Sword", 
	AssetId = 0x1b, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Sword",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "A sword pulsing with the powerful magic of ancient beings.",
	Projectile = {
		Bullet = "Fire Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 210,
		MaxDamage = 255,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1c] = {Title = "Skysplitter Sword", 
	AssetId = 0x1c, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Sword",
	Tier = 10,
	BagType = "White Bag",
	Description = "An unfathomably powerful sword wielded by titanic air elementals in their great war of revolution.",
	Projectile = {
		Bullet = "Blue Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 210,
		MaxDamage = 270,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1d] = {Title = "Sword of Acclaim", 
	AssetId = 0x1d, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Sword",
	Tier = 11,
	BagType = "White Bag",
	Description = "A great sword of recognition, forged by the gods for the champions of humankind.",
	Projectile = {
		Bullet = "Purple Bolt",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 220,
		MaxDamage = 275,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1e] = {Title = "Sword of Splendor", 
	AssetId = 0x1e, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1684431861",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Sword",
	Tier = 12,
	BagType = "White Bag",
	Description = "An exalted weapon of the august kings of old, hallowed with the spirit of nations and yearning to grant power anew.",
	Projectile = {
		Bullet = "Splendor Shot",
		Range = 3.5*Constants.STATS.TileSize,
		MinDamage = 225,
		MaxDamage = 280,
		Lifetime = 3.5*Constants.STATS.TileSize/16,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x1f] = {Title = "Shortbow", 
	AssetId = 0x1f, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Bow",
	Tier = 0,
	Description = "A well-made shortbow.",
	Projectile = {
		Bullet = "Green Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 15,
		MaxDamage = 45,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x21] = {Title = "Reinforced Bow", 
	AssetId = 0x21, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Bow",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "An iron-reinforced bow.",
	Projectile = {
		Bullet = "Green Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 20,
		MaxDamage = 50,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x5] = {Title = "Crossbow", 
	AssetId = 0x5, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Bow",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A bow mounted on a stock that shoots with amazing speed and accuracy.",
	Projectile = {
		Bullet = "Crossbow Bolt",
		Range = 7.5*Constants.STATS.TileSize,
		MinDamage = 25,
		MaxDamage = 60,
		Lifetime = 7.5*Constants.STATS.TileSize/26.63,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x22] = {Title = "Greywood Bow", 
	AssetId = 0x22, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Bow",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "A bow made from the rare greywood tree.",
	Projectile = {
		Bullet = "Green Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 30,
		MaxDamage = 65,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x23] = {Title = "Ironwood Bow", 
	AssetId = 0x23, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Bow",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "A high-quality bow made of magical ironwood.",
	Projectile = {
		Bullet = "Green Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 40,
		MaxDamage = 70,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x24] = {Title = "Fire Bow", 
	AssetId = 0x24, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Bow",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "A bow that shoots arrows that burn with an unholy fire.",
	Projectile = {
		Bullet = "Fire Missile",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 50,
		MaxDamage = 75,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x25] = {Title = "Double Bow", 
	AssetId = 0x25, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Bow",
	Tier = 6,
	BagType = "Brown Bag",
	Description = "A bow that somehow manages to shoot two arrows in different directions.",
	Projectile = {
		Bullet = "Blue Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 30,
		MaxDamage = 55,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 2,
		Angle = 15,
	},}
,
[0x26] = {Title = "Heavy Crossbow", 
	AssetId = 0x26, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Bow",
	Tier = 7,
	BagType = "Blue Bag",
	Description = "A slow but powerful crossbow with a good grip.",
	Projectile = {
		Bullet = "Heavy Crossbow Bolt",
		Range = 7.5*Constants.STATS.TileSize,
		MinDamage = 55,
		MaxDamage = 80,
		Lifetime = 7.5*Constants.STATS.TileSize/27,
		NumProjectiles = 1,
		Angle = 0,
	},}
,
[0x27] = {Title = "Golden Bow", 
	AssetId = 0x27, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Bow",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "A bow gifted to mortals from the gods themselves. It shoots powerful arrows in three directions at once.",
	Projectile = {
		Bullet = "Gold Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 40,
		MaxDamage = 61,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 3,
		Angle = 8,
	},}
,
[0x28] = {Title = "Verdant Bow", 
	AssetId = 0x28, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Bow",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "A highly effective bow fashioned out of still-living magical springwood.",
	Projectile = {
		Bullet = "Green Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 45,
		MaxDamage = 67,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 3,
		Angle = 8,
	},}
,
[0x29] = {Title = "Bow of Fey Magic", 
	AssetId = 0x29, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Bow",
	Tier = 10,
	BagType = "White Bag",
	Description = "A powerful bow crafted by dryads and blessed by the spirits of the woodlands.",
	Projectile = {
		Bullet = "Blue Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 48,
		MaxDamage = 75,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 3,
		Angle = 8,
	},}
,
[0x2a] = {Title = "Bow of Innocent Blood", 
	AssetId = 0x2a, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(512, 768),
	SlotType = "Bow",
	Tier = 11,
	BagType = "White Bag",
	Description = "A runed bow steeped in the dark power of ancient injustice.",
	Projectile = {
		Bullet = "Red Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 50,
		MaxDamage = 80,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 3,
		Angle = 8,
	},}
,
[0x2b] = {Title = "Bow of Covert Havens", 
	AssetId = 0x2b, 
	AssetType = "Weapon", 
	Image = "rbxassetid://1682999020",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Bow",
	Tier = 12,
	BagType = "White Bag",
	Description = "A diamondwire bow used by guardians of the unseen ethereal shrines.",
	Projectile = {
		Bullet = "Blue Arrow",
		Range = 7.04*Constants.STATS.TileSize,
		MinDamage = 55,
		MaxDamage = 85,
		Lifetime = 7.04*Constants.STATS.TileSize/25,
		NumProjectiles = 3,
		Angle = 8,
	},}
,
[0x2c] = {Title = "Potion of Attack", 
	AssetId = 0x2c, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases attack power by 1.",
	Stats = {
		Attack = 1,
	},}
,
[0x2d] = {Title = "Potion of Defense", 
	AssetId = 0x2d, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases defense power by 1.",
	Stats = {
		Defense = 1,
	},}
,
[0x2e] = {Title = "Potion of Speed", 
	AssetId = 0x2e, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases speed by 1.",
	Stats = {
		Speed = 1,
	},}
,
[0x2f] = {Title = "Potion of Dexterity", 
	AssetId = 0x2f, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases dexterity by 1.",
	Stats = {
		Dexterity = 1,
	},}
,
[0x30] = {Title = "Potion of Vitality", 
	AssetId = 0x30, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases health regen by 1.",
	Stats = {
		HealthRegen = 1,
	},}
,
[0x31] = {Title = "Potion of Wisdom", 
	AssetId = 0x31, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases energy regen by 1.",
	Stats = {
		EnergyRegen = 1,
	},}
,
[0x32] = {Title = "Potion of Energy", 
	AssetId = 0x32, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases energy by 5.",
	Stats = {
		Energy = 5,
	},}
,
[0x33] = {Title = "Potion of Life", 
	AssetId = 0x33, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that permanently increases health by 5.",
	Stats = {
		Health = 5,
	},}
,
[0x34] = {Title = "Loot Drop Potion", 
	AssetId = 0x34, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that causes enemies to drop more loot! Lasts 30 minutes.",
	Timer = 1800,} --30 minutes
,
[0x35] = {Title = "Loot Tier Potion", 
	AssetId = 0x35, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "A potion that boosts the tier level of dropped loot. Lasts 30 minutes.",
	Timer = 1800,} --30 minutes
,
[0x36] = {Title = "XP Booster", 
	AssetId = 0x36, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "Get 2X all XP gained for 20 minutes!",
	Timer = 1200,} --20 minutes
,
[0x37] = {Title = "XP Booster", 
	AssetId = 0x37, 
	AssetType = "Consumable", 
	Image = "rbxassetid://1818057468",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Potion",
	Tier = 2,
	BagType = "White Bag",
	Description = "Get 2X all XP gained for 1 hour!",
	Timer = 3600,} --60 minutes
,
[0x38] = {Title = "Robe of the Guest", 
	AssetId = 0x38, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Robe",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A friendly, hospitable robe blessed with the souls of past guests.",
	Stats = {
		Defense = 2,
	},}
,
[0x39] = {Title = "Robe of the Neophyte", 
	AssetId = 0x39, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Robe",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A long woolen robe favored by students of magic.",
	Stats = {
		Defense = 3,
		EnergyRegen = 1,
	},}
,
[0x3a] = {Title = "Robe of the Apprentice", 
	AssetId = 0x3a, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Robe",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "A robe woven of rare yellow silk.",
	Stats = {
		Defense = 4,
		EnergyRegen = 1,
		Energy = 10,
	},}
,
[0x3b] = {Title = "Robe of the Acolyte", 
	AssetId = 0x3b, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Robe",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "A well-made robe of enchanted blue silk.",
	Stats = {
		Defense = 4,
		EnergyRegen = 2,
		Energy = 15,
	},}
,
[0x3c] = {Title = "Robe of the Student", 
	AssetId = 0x3c, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Robe",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "A magical robe of faintly glowing wizardcloth.",
	Stats = {
		Defense = 6,
		EnergyRegen = 2,
		Energy = 20,
	},}
,
[0x3d] = {Title = "Robe of the Conjurer", 
	AssetId = 0x3d, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Robe",
	Tier = 6,
	BagType = "Brown Bag",
	Description = "A magical robe of gray moonsilk.",
	Stats = {
		Defense = 7,
		EnergyRegen = 3,
		Energy = 25,
	},}
,
[0x3e] = {Title = "Robe of the Adept", 
	AssetId = 0x3e, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Robe",
	Tier = 7,
	BagType = "Brown Bag",
	Description = "An enchanted robe of dark moonweave.",
	Stats = {
		Defense = 8,
		EnergyRegen = 3,
		Energy = 30,
	},}
,
[0x3f] = {Title = "Robe of the Invoker", 
	AssetId = 0x3f, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Robe",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "A powerful robe of delicately embroidered red feythread.",
	Stats = {
		Attack = 1,
		Defense = 8,
		EnergyRegen = 4,
		Energy = 35,
	},}
,
[0x40] = {Title = "Robe of the Illusionist", 
	AssetId = 0x40, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Robe",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "A highly decorated robe of purple wizardcloth, imbued with powers of sorcery and darkness.",
	Stats = {
		Attack = 2,
		Defense = 9,
		EnergyRegen = 5,
		Energy = 40,
	},}
,
[0x41] = {Title = "Robe of the Moon Wizard", 
	AssetId = 0x41, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Robe",
	Tier = 10,
	BagType = "Blue Bag",
	Description = "A robe of rarest moonsilk, enhanced long ago with deep nocturnal enchantments.",
	Stats = {
		Attack = 2,
		Defense = 10,
		EnergyRegen = 5,
		Energy = 45,
	},}
,
[0x42] = {Title = "Robe of the Master", 
	AssetId = 0x42, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Robe",
	Tier = 11,
	BagType = "White Bag",
	Description = "A brightly colored robe of metallic threads, woven in the ancient elvish style and steeped in fey auras.",
	Stats = {
		Attack = 3,
		Defense = 11,
		EnergyRegen = 6,
		Energy = 50,
	},}
,
[0x43] = {Title = "Robe of the Supreme Warlock", 
	AssetId = 0x43, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Robe",
	Tier = 12,
	BagType = "White Bag",
	Description = "A bloodweft robe adorned with rubies and firegarnets, worn by an ancient sect of masterful wizards.",
	Stats = {
		Attack = 3,
		Defense = 12,
		EnergyRegen = 6,
		Energy = 50,
	},}
,
[0x44] = {Title = "Robe of the Grand Sorcerer", 
	AssetId = 0x44, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125246",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Robe",
	Tier = 13,
	BagType = "White Bag",
	Description = "A robe of gossamer glowthread, used by the sorceress matriarchs of the western kingdoms.",
	Stats = {
		Attack = 4,
		Defense = 13,
		EnergyRegen = 6,
		Energy = 55,
	},}
,
[0x45] = {Title = "Guest Armor", 
	AssetId = 0x45, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Heavy Armor",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "Armor crafted by the spirit of lost guests.",
	Stats = {
		Defense = 5,
	},}
,
[0x46] = {Title = "Iron Mail", 
	AssetId = 0x46, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Heavy Armor",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "Armor made from interlocking iron links.",
	Stats = {
		Defense = 6,
	},}
,
[0x47] = {Title = "Chain Mail", 
	AssetId = 0x47, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Heavy Armor",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "Armor made from interlocking links of metal.",
	Stats = {
		Defense = 7,
	},}
,
[0x48] = {Title = "Blue Steel Mail", 
	AssetId = 0x48, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Heavy Armor",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "Mail made from blued steel.",
	Stats = {
		Defense = 8,
	},}
,
[0x49] = {Title = "Silver Chainmail", 
	AssetId = 0x49, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Heavy Armor",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "Well-made chainmail plated with silver.",
	Stats = {
		Defense = 10,
	},}
,
[0x4a] = {Title = "Golden Chainmail", 
	AssetId = 0x4a, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Heavy Armor",
	Tier = 6,
	BagType = "Brown Bag",
	Description = "Well-made chainmail plated with gold, clearly intended for the use of a great lord.",
	Stats = {
		Defense = 12,
	},}
,
[0x4b] = {Title = "Plate Mail", 
	AssetId = 0x4b, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Heavy Armor",
	Tier = 7,
	BagType = "Brown Bag",
	Description = "Armor made from overlapping plates of metal.",
	Stats = {
		Defense = 13,
	},}
,
[0x4c] = {Title = "Mithril Chainmail", 
	AssetId = 0x4c, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Heavy Armor",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "Chainmail made with reinforcing mithril ribs.",
	Stats = {
		Defense = 15,
	},}
,
[0x4d] = {Title = "Mithril Armor", 
	AssetId = 0x4d, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Heavy Armor",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "Armor made from the strongest and most desirable of all metals.",
	Stats = {
		Defense = 20,
	},}
,
[0x4e] = {Title = "Dragonscale Armor", 
	AssetId = 0x4e, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Heavy Armor",
	Tier = 10,
	BagType = "Blue Bag",
	Description = "Armor made from the scales of a full grown dragon.",
	Stats = {
		Defense = 21,
	},}
,
[0x4f] = {Title = "Desolation Armor", 
	AssetId = 0x4f, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Heavy Armor",
	Tier = 11,
	BagType = "White Bag",
	Description = "Magical cold plate armor inscribed with tales of destruction and murder.",
	Stats = {
		Defense = 22,
	},}
,
[0x50] = {Title = "Vengeance Armor", 
	AssetId = 0x50, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Heavy Armor",
	Tier = 12,
	BagType = "White Bag",
	Description = "Tremendously strong plate armor shrouded by an aura of demonic revenge.",
	Stats = {
		Defense = 23,
	},}
,
[0x51] = {Title = "Abyssal Armor", 
	AssetId = 0x51, 
	AssetType = "Armor", 
	Image = "rbxassetid://1887125916",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Heavy Armor",
	Tier = 13,
	BagType = "White Bag",
	Description = "Mighty felplate armor designed for the most powerful of demon lords.",
	Stats = {
		Defense = 24,
	},}
,
[0x52] = {Title = "Guest Hide Armor", 
	AssetId = 0x52, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Leather Armor",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "Leather armor made from guestcloth.",
	Stats = {
		Defense = 5,
	},}
,
[0x53] = {Title = "Wolfskin Armor", 
	AssetId = 0x53, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Leather Armor",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "Leather armor fashioned from wolf pelts.",
	Stats = {
		Defense = 6,
	},}
,
[0x54] = {Title = "Leather Armor", 
	AssetId = 0x54, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Leather Armor",
	Tier = 3,
	BagType = "Brown Bag",
	Description = "Armor made of hardened leather.",
	Stats = {
		Defense = 7,
	},}
,
[0x55] = {Title = "Basilisk Hide Armor", 
	AssetId = 0x55, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Leather Armor",
	Tier = 4,
	BagType = "Brown Bag",
	Description = "Leather armor made from the skin of a magical lizard.",
	Stats = {
		Defense = 8,
		Dexterity = 2,
	},}
,
[0x56] = {Title = "Minotaur Hide Armor", 
	AssetId = 0x56, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Leather Armor",
	Tier = 5,
	BagType = "Brown Bag",
	Description = "Leather armor made from the tough hide of a minotaur.",
	Stats = {
		Defense = 9,
		Dexterity = 2,
	},}
,
[0x57] = {Title = "Bearskin Armor", 
	AssetId = 0x57, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Leather Armor",
	Tier = 6,
	BagType = "Brown Bag",
	Description = "Armor made from the thick leather of a dire bear.",
	Stats = {
		Defense = 10,
		Dexterity = 2,
	},}
,
[0x58] = {Title = "Chimera Hide Armor", 
	AssetId = 0x58, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Leather Armor",
	Tier = 7,
	BagType = "Brown Bag",
	Description = "Magically protective leather armor made from chimera hides.",
	Stats = {
		Defense = 12,
		Dexterity = 2,
	},}
,
[0x59] = {Title = "Wyvern Skin Armor", 
	AssetId = 0x59, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Leather Armor",
	Tier = 8,
	BagType = "Blue Bag",
	Description = "Tough, durable armor made from wyvern leather.",
	Stats = {
		Defense = 13,
		Dexterity = 3,
	},}
,
[0x5a] = {Title = "Studded Leather Armor", 
	AssetId = 0x5a, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Leather Armor",
	Tier = 9,
	BagType = "Blue Bag",
	Description = "Leather armor studded with metal rivets that provide extra protection.",
	Stats = {
		Defense = 14,
		Dexterity = 3,
	},}
,
[0x5b] = {Title = "Drake Hide Armor", 
	AssetId = 0x5b, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Leather Armor",
	Tier = 10,
	BagType = "Blue Bag",
	Description = "Leather armor fashioned from the scaly skin of a fire breathing drake.",
	Stats = {
		Defense = 15,
		Dexterity = 4,
	},}
,
[0x5c] = {Title = "Roc Leather Armor", 
	AssetId = 0x5c, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Leather Armor",
	Tier = 11,
	BagType = "White Bag",
	Description = "Leather armor made from the durable hide of a roc.",
	Stats = {
		Defense = 16,
		Dexterity = 4,
	},}
,
[0x5d] = {Title = "Hippogriff Hide Armor", 
	AssetId = 0x5d, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Leather Armor",
	Tier = 12,
	BagType = "White Bag",
	Description = "Leather armor made from the protective skin of hippogriffs.",
	Stats = {
		Defense = 17,
		Dexterity = 4,
	},}
,
[0x5e] = {Title = "Griffon Hide Armor", 
	AssetId = 0x5e, 
	AssetType = "Armor", 
	Image = "rbxassetid://1901610991",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Leather Armor",
	Tier = 13,
	BagType = "White Bag",
	Description = "Superior leather armor made from the magical hide of a griffon.",
	Stats = {
		Defense = 17,
		Dexterity = 5,
	},}
,
[0x5f] = {Title = "Ring of Defense", 
	AssetId = 0x5f, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "An onyx set in a gold ring.",
	Stats = {
		Defense = 3,
	},}
,
[0x63] = {Title = "Ring of Superior Defense", 
	AssetId = 0x63, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "An onyx mounted on a gold ring.",
	Stats = {
		Defense = 5,
	},}
,
[0x64] = {Title = "Ring of Paramount Defense", 
	AssetId = 0x64, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "An onyx mounted on a two-pronged gold ring.",
	Stats = {
		Defense = 7,
	},}
,
[0x65] = {Title = "Ring of Exalted Defense", 
	AssetId = 0x65, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless onyx set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Defense = 8,
	},}
,
[0x60] = {Title = "Ring of Speed", 
	AssetId = 0x60, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "An emerald set in a gold ring.",
	Stats = {
		Speed = 3,
	},}
,
[0x66] = {Title = "Ring of Superior Speed", 
	AssetId = 0x66, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(256, 768),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "An emerald mounted on a gold ring.",
	Stats = {
		Speed = 5,
	},}
,
[0x67] = {Title = "Ring of Paramount Speed", 
	AssetId = 0x67, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(512, 768),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "An emerald mounted on a two-pronged gold ring.",
	Stats = {
		Speed = 7,
	},}
,
[0x68] = {Title = "Ring of Exalted Speed", 
	AssetId = 0x68, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(768, 768),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless emerald set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Speed = 8,
	},}
,
[0x61] = {Title = "Ring of Health", 
	AssetId = 0x61, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A topaz set in a gold ring.",
	Stats = {
		Health = 40,
	},}
,
[0x69] = {Title = "Ring of Superior Health", 
	AssetId = 0x69, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A topaz mounted on a gold ring.",
	Stats = {
		Health = 80,
	},}
,
[0x6a] = {Title = "Ring of Paramount Health", 
	AssetId = 0x6a, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "A topaz mounted on a two-pronged gold ring.",
	Stats = {
		Health = 120,
	},}
,
[0x6b] = {Title = "Ring of Exalted Health", 
	AssetId = 0x6b, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless topaz set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Health = 140,
	},}
,
[0x62] = {Title = "Ring of Wisdom", 
	AssetId = 0x62, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A sapphire set in a gold ring.",
	Stats = {
		["nergy Regen"] = 3,
	},}
,
[0x6c] = {Title = "Ring of Superior Wisdom", 
	AssetId = 0x6c, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A sapphire mounted on a gold ring.",
	Stats = {
		["Energy Regen"] = 5,
	},}
,
[0x6d] = {Title = "Ring of Paramount Wisdom", 
	AssetId = 0x6d, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "A sapphire mounted on a two-pronged gold ring.",
	Stats = {
		["Energy Regen"] = 7,
	},}
,
[0x6e] = {Title = "Ring of Exalted Wisdom", 
	AssetId = 0x6e, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901612114",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless sapphire set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		["Energy Regen"] = 8,
	},}
,
[0x6f] = {Title = "Ring of Attack", 
	AssetId = 0x6f, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(0, 256),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A spinel set in a gold ring.",
	Stats = {
		Attack = 3,
	},}
,
[0x70] = {Title = "Ring of Superior Attack", 
	AssetId = 0x70, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(256, 256),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A spinel mounted on a gold ring.",
	Stats = {
		Attack = 5,
	},}
,
[0x71] = {Title = "Ring of Paramount Attack", 
	AssetId = 0x71, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(512, 256),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "A spinel mounted on a two-pronged gold ring.",
	Stats = {
		Attack = 7,
	},}
,
[0x72] = {Title = "Ring of Exalted Attack", 
	AssetId = 0x72, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(768, 256),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless sapphire set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Attack = 8,
	},}
,
[0x73] = {Title = "Ring of Dexterity", 
	AssetId = 0x73, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(0, 0),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A citrine set in a gold ring.",
	Stats = {
		Dexterity = 3,
	},}
,
[0x74] = {Title = "Ring of Superior Dexterity", 
	AssetId = 0x74, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(256, 0),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A citrine mounted on a gold ring.",
	Stats = {
		Dexterity = 5,
	},}
,
[0x75] = {Title = "Ring of Paramount Dexterity", 
	AssetId = 0x75, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(512, 0),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "A citrine mounted on a two-pronged gold ring.",
	Stats = {
		Dexterity = 7,
	},}
,
[0x76] = {Title = "Ring of Exalted Dexterity", 
	AssetId = 0x76, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(768, 0),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless citrine set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Dexterity = 8,
	},}
,
[0x77] = {Title = "Ring of Vitality", 
	AssetId = 0x77, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(0, 512),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "A ruby set in a gold ring.",
	Stats = {
		["Health Regen"] = 3,
	},}
,
[0x78] = {Title = "Ring of Superior Vitality", 
	AssetId = 0x78, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(256, 512),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "A ruby mounted on a gold ring.",
	Stats = {
		["Health Regen"] = 5,
	},}
,
[0x79] = {Title = "Ring of Paramount Vitality", 
	AssetId = 0x79, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(512, 512),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "A ruby mounted on a two-pronged gold ring.",
	Stats = {
		["Health Regen"] = 7,
	},}
,
[0x7a] = {Title = "Ring of Exalted Vitality", 
	AssetId = 0x7a, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(768, 512),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless ruby set in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		["Health Regen"] = 8,
	},}
,
[0x7b] = {Title = "Ring of Energy", 
	AssetId = 0x7b, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(0, 768),
	SlotType = "Accessory",
	Tier = 1,
	BagType = "Brown Bag",
	Description = "An amethyst set in a gold ring.",
	Stats = {
		Energy = 40,
	},}
,
[0x7c] = {Title = "Ring of Superior Energy", 
	AssetId = 0x7c, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(256, 768),
	SlotType = "Accessory",
	Tier = 2,
	BagType = "Brown Bag",
	Description = "An amethyst mounted on a gold ring.",
	Stats = {
		Energy = 80,
	},}
,
[0x7d] = {Title = "Ring of Paramount Energy", 
	AssetId = 0x7d, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(512, 768),
	SlotType = "Accessory",
	Tier = 3,
	BagType = "Blue Bag",
	Description = "An amethyst mounted on a two-pronged gold ring.",
	Stats = {
		Energy = 120,
	},}
,
[0x7e] = {Title = "Ring of Exalted Energy", 
	AssetId = 0x7e, 
	AssetType = "Accessory", 
	Image = "rbxassetid://1901625851",
	ImageRectOffset = Vector2.new(768, 768),
	SlotType = "Accessory",
	Tier = 4,
	BagType = "White Bag",
	Description = "A flawless amethyst mounted in a stunningly beatiful gold ring dazzled with side-stones.",
	Stats = {
		Energy = 140,
	},}
,
}
