
local Constants = require(game.ReplicatedStorage:WaitForChild("Constants"))
return {
[1] = {Title = "Bat", 
	AssetId = 1, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Dead, 	
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 4.5,
	Projectile = {
		[1] = {
			Bullet = "OrangeCylinder",
			Damage = 55,
			Range = 70,
			Lifetime = 1,
			NumProjectiles = 5,
			Angle = math.pi/6,
		}
	},
	Health = 100,
	WalkDistance = 10,
	Range = 40,
},
[2] = {Title = "Cubex", 
	AssetId = 2, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.AllBiomes, 	
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 1,
	Projectile = {
		[1] = {
			Bullet = "PurpleCylinder",
			Damage = 15,
			Range = 70,
			Lifetime = 1,	
			NumProjectiles = 3,
			Angle = math.pi/12,
		}
	},
	Health = 50,
	WalkDistance = 10,
	Range = 40,
},
[3] = {Title = "Dragon Boar", 
	AssetId = 3, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Desert, 	
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 3.5,
	Projectile = {
		[1] = {
			Bullet = "TanWedge",
			Damage = 50,
			Range = 54,
			Lifetime = 1.2,
			NumProjectiles = 1,
			Angle = 0,
		}
	},
	Health = 130,
	WalkDistance = 10,
	Range = 50,
},
[4] = {Title = "Ghost", 
	AssetId = 4, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Dead, 	
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 4,
	Projectile = {
		[1] = {
			Bullet = "BlueWedge",
			Damage = 40,
			Range = 70,
			Lifetime = 1,
			NumProjectiles = 2,
			Angle = math.pi/10,
		}
	},
	Health = 75,
	WalkDistance = 10,
	Range = 40,
},
[5] = {Title = "Golem", 
	AssetId = 5, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Highlands, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 2.5,
	Projectile = {
		[1] = {
			Bullet = "BrownBall",
			Damage = 120,
			Range = 88,
			Lifetime = 1.1,
			NumProjectiles = 3,
			Angle = math.pi/12,
		}
	},
	Health = 300,
	WalkDistance = 10,
	Range = 60,
},
[6] = {Title = "Minotaur", 
	AssetId = 6, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Midlands, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 4.5,
	Projectile = {
		[1] = {
			Bullet = "BrownCube",
			Damage = 95,
			Range = 66,
			Lifetime = 1.1,
			NumProjectiles = 5,
			Angle = math.pi/6,
		}
	},
	Health = 150,
	WalkDistance = 10,
	Range = 60,
},
[7] = {Title = "Rabbit", 
	AssetId = 7, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Enum.Material.LeafyGrass.Value, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 1,
	Projectile = {
		[1] = {
			Bullet = "BlueBall",
			Damage = 25,
			Range = 85,
			Lifetime = 1.1,
			NumProjectiles = 2,
			Angle = math.pi/10,
		}
	},
	Health = 90,
	WalkDistance = 10,
	Range = 40,
},
[8] = {Title = "Skeleton", 
	AssetId = 8, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Dead, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 2.5,
	Projectile = {
		[1] = {
			Bullet = "WhiteWedge",
			Damage = 45,
			Range = 70,
			Lifetime = 1,
			NumProjectiles = 2,
			Angle = math.pi/12,
		}
	},
	Health = 140,
	WalkDistance = 10,
	Range = 40,
},
[9] = {Title = "Slime", 
	AssetId = 9, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Enum.Material.Mud.Value, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 5,
	Projectile = {
		[1] = {
			Bullet = "GreenCube",
			Damage = 55,
			Range = 70,
			Lifetime = 1,
			NumProjectiles = 3,
			Angle = math.pi/10,
		}
	},
	Health = 70,
	WalkDistance = 10,
	Range = 40,
},
[10] = {Title = "Zebra", 
	AssetId = 10, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Enum.Material.Grass.Value, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 1,
	Projectile = {
		[1] = {
			Bullet = "BeigeCylinder",
			Damage = 40,
			Range = 70,
			Lifetime = 1,
			NumProjectiles = 2,
			Angle = math.pi/8,
		}
	},
	Health = 100,
	WalkDistance = 10,
	Range = 40,
},
[11] = {Title = "Zebu", 
	AssetId = 11, 
	AssetType = Constants.ASSET_TYPE.Mob, 
	BiomeType = Constants.BIOME.Lowlands, 
	DungeonType = Constants.DUNGEON.NoDungeons,
	SpawnChance = 2, 
	XPMult = 1,
	Projectile = {
		[1] = {
			Bullet = "OrangeCube",
			Damage = 35,
			Range = 80,
			Lifetime = 1,
			NumProjectiles = 1,
			Angle = 0,
		}
	},
	Health = 80,
	WalkDistance = 10,
	Range = 40,
},
[12] = {Title = "Vox",
	AssetId = 12,
	AssetType = Constants.ASSET_TYPE.Mob,
	BiomeType = Constants.BIOME.NoBiomes,
	DungeonType = Constants.DUNGEON.VoxsCastle,
	XPMult = 0.1,
	Boss = true,
	Projectile = {
		[1] = {
			Bullet = "WhiteBall",
			Damage = 90,
			Range = 100,
			Lifetime = 3,
			NumProjectiles = 16,
			Angle = math.pi/8,
		},
		[2] = {
			Bullet = "BlackBall",
			Damage = 160,
			Range = 65,
			Lifetime = 3,
			NumProjectiles = 32,
			Angle = math.pi/16,
		},
		[3] = {
			Bullet = "DoubleWhite",
			Damage = 210,
			Range = 100,
			Lifetime = 2,
			NumProjectiles = 1,
			Angle = 0,
		},
		[4] = {
			Bullet = "YellowPlumbob",
			Damage = 40,
			Range = 100,
			Lifetime = 1.5,
			NumProjectiles = 8,
			Angle = math.pi/4,
		},
	},
	Health = 85000,
	WalkDistance = 10,
	Range = 50,
},
}
